name: client_gp

services:
  database:
    image: postgres:15
    container_name: postgres_gp

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5


  backend:
    image: gestione-proxy-backend:dev
    container_name: bke-gp

    build:
      context: ./backend

    ports:
      - "6812:8100"

    volumes:
      - ./backend:/app

    depends_on:
      database:
        condition: service_healthy

    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      ADMIN_USERNAME: ${ADMIN_USERNAME:-admin}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-password}


  frontend:
    image: gestione-proxy-frontend:dev
    container_name: fe-gp

    build:
      context: ./frontend

    ports:
      - "3010:3000"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    environment:
      CHOKIDAR_USEPOLLING: "true"
      VITE_API_URL: ${VITE_API_URL}

    depends_on:
      - backend

    stdin_open: true
    tty: true


volumes:
  postgres_data:
